"use client";

import { useEffect, useRef, useState } from "react";
import { Loader2, Upload, User } from "lucide-react";
import TeamDisplay from "./TeamDisplay";
import { MatchEditorPlayer, MatchEditorResult, MatchSide, PreparedMatchResultImage, majoritySide, matchEditorResultKey, validateMatchEditorResult } from "../lib/matchRegistration";
import { prepareMatchResultImage } from "../lib/matchResultPreview";

interface Team { team_number:number; characters:Array<{id:number|null;collection_level:string|null}> }
interface Character { id:number; name:string; is_template_available?:boolean; icon_url?:string }
interface Props {
  attacker: MatchEditorPlayer; defender: MatchEditorPlayer;
  attackerTeams?: Team[]; defenderTeams?: Team[]; characters?: Character[];
  initialResult?: MatchEditorResult | null; existing?: boolean; disabled?: boolean; busy?: boolean; error?: string;
  dependencyWarning?: string;
  onAnalyze: (file: File) => Promise<MatchEditorResult>;
  onSave: (result: MatchEditorResult) => Promise<void>;
  onClose?: () => void;
  onDirtyChange?: (dirty:boolean) => void;
}

export default function MatchResultEditor({attacker,defender,attackerTeams=[],defenderTeams=[],characters=[],initialResult=null,existing=false,disabled=false,busy=false,error="",dependencyWarning,onAnalyze,onSave,onClose,onDirtyChange}:Props){
  const [preparedImage,setPreparedImage]=useState<PreparedMatchResultImage|null>(null); const [originalPreview,setOriginalPreview]=useState<string|null>(null); const [modalPreview,setModalPreview]=useState<string|null>(null); const [showOriginal,setShowOriginal]=useState(false); const [preparing,setPreparing]=useState(false); const [previewError,setPreviewError]=useState(false); const [result,setResult]=useState<MatchEditorResult|null>(initialResult); const [dirty,setDirty]=useState(false); const [resultDirty,setResultDirty]=useState(false); const [analysisApplied,setAnalysisApplied]=useState(false); const inputRef=useRef<HTMLInputElement>(null); const generation=useRef(0); const analysisInFlight=useRef(false); const originalPreviewRef=useRef<string|null>(null); const modalPreviewRef=useRef<string|null>(null); const initialResultRef=useRef(initialResult); initialResultRef.current=initialResult; const initialResultKey=matchEditorResultKey(initialResult);
  useEffect(()=>{setResult(initialResultRef.current);setDirty(false);setResultDirty(false);setAnalysisApplied(false);},[attacker.id,defender.id,initialResultKey]);
  useEffect(()=>onDirtyChange?.(dirty),[dirty,onDirtyChange]);
  const releasePreviews=()=>{if(originalPreviewRef.current)URL.revokeObjectURL(originalPreviewRef.current);if(modalPreviewRef.current)URL.revokeObjectURL(modalPreviewRef.current);originalPreviewRef.current=null;modalPreviewRef.current=null;};
  useEffect(()=>()=>{generation.current+=1;releasePreviews();},[]);
  const choose=async(next:File|null,saved=false)=>{const current=++generation.current;releasePreviews();setPreparedImage(null);setOriginalPreview(null);setModalPreview(null);setShowOriginal(false);setPreviewError(false);setDirty(saved?false:next?true:resultDirty);if(!next){setPreparing(false);if(inputRef.current)inputRef.current.value="";return;}const sourceUrl=URL.createObjectURL(next);originalPreviewRef.current=sourceUrl;setOriginalPreview(sourceUrl);setPreparing(true);try{const prepared=await prepareMatchResultImage(next);if(current!==generation.current)return;setPreparedImage(prepared);if(prepared.isModalCrop){const cropUrl=URL.createObjectURL(prepared.previewFile);modalPreviewRef.current=cropUrl;setModalPreview(cropUrl);}else{setPreviewError(true);}}catch{if(current===generation.current){setPreparedImage({originalFile:next,uploadFile:next,previewFile:next,isModalCrop:false});setPreviewError(true);}}finally{if(current===generation.current)setPreparing(false);}};
  const close=()=>{if(busy)return;if(dirty&&!window.confirm("未保存の勝敗修正を破棄しますか？"))return;onClose?.();};
  const updateRound=(number:number,winner:MatchSide|null)=>{setResult(current=>current?{...current,issues:[],rounds:current.rounds.map(round=>round.roundNumber===number?{...round,winner}:round)}:current);setDirty(true);setResultDirty(true);};
  const issues=validateMatchEditorResult(result); const winner=result?majoritySide(result.rounds):null;
  const teams=(label:string,items:Team[])=><div className="space-y-1"><p className="text-xs font-bold text-slate-400">{label}の5部隊</p>{items.length?[...items].sort((a,b)=>a.team_number-b.team_number).map(team=><div key={team.team_number} className="flex items-center gap-2 rounded-lg bg-slate-950/50 p-2"><span className="w-7 text-xs font-black text-slate-500">R{team.team_number}</span><TeamDisplay charIds={team.characters.map(c=>c.id??9999)} collectionLevels={team.characters.map(c=>c.collection_level)} allCharacters={characters as any}/></div>):<p className="text-xs text-slate-500">編成情報を表示できません。</p>}</div>;
  const player=(side:"攻撃側（左）"|"防衛側（右）",p:MatchEditorPlayer)=><div className="flex items-center gap-3 rounded-xl bg-slate-800/70 p-3"><div className="flex h-12 w-12 items-center justify-center overflow-hidden rounded-full bg-slate-950">{p.iconUrl?<img src={p.iconUrl} alt="" className="h-full w-full object-cover"/>:<User size={18}/>}</div><div><p className="text-xs font-bold text-slate-400">{side}</p><b>{p.name}</b>{p.detail&&<p className="text-xs text-slate-400">{p.detail}</p>}</div></div>;
  return <section className="space-y-5" data-match-result-editor>
    <div className="grid gap-3 sm:grid-cols-2">{player("攻撃側（左）",attacker)}{player("防衛側（右）",defender)}</div>
    <div className="grid gap-4 lg:grid-cols-2">{teams(attacker.name,attackerTeams)}{teams(defender.name,defenderTeams)}</div>
    {dependencyWarning&&<div className="rounded-xl border border-amber-700/50 bg-amber-950/30 p-3 text-sm text-amber-200">{dependencyWarning}</div>}
    {error&&<div role="alert" className="rounded-xl bg-red-950/50 p-3 text-red-300">{error}</div>}
    {!disabled&&<><div className="min-w-0 overflow-hidden rounded-xl border border-white/10 bg-slate-800/50 p-3 sm:p-4">{originalPreview?<div className="mx-auto min-w-0 max-w-4xl space-y-3">{preparing?<div role="status" className="flex min-h-48 items-center justify-center gap-2 text-emerald-300"><Loader2 className="animate-spin"/>勝敗結果部分を準備中...</div>:<><div className="flex flex-wrap items-center justify-between gap-2"><b className="text-sm text-slate-200">{modalPreview&&!showOriginal?"解析対象部分":"元画像"}</b>{modalPreview&&<button type="button" disabled={busy} onClick={()=>setShowOriginal(value=>!value)} className="rounded-lg bg-slate-700 px-3 py-2 text-xs font-bold">{showOriginal?"解析対象部分を表示":"元画像を確認"}</button>}</div>{previewError&&<p role="status" className="rounded-lg bg-amber-950/40 p-3 text-sm text-amber-200">勝敗結果部分を切り出せなかったため、元画像を表示しています。</p>}<div className="flex max-h-[32rem] w-full min-w-0 items-center justify-center overflow-hidden rounded-lg bg-slate-950/70"><img src={modalPreview&&!showOriginal?modalPreview:originalPreview} alt={modalPreview&&!showOriginal?"AIが解析する勝敗結果部分":"選択したリザルト元画像"} className="max-h-[32rem] max-w-full object-contain"/></div></>}<button type="button" disabled={busy||preparing} onClick={()=>void choose(null)} className="w-full rounded-lg bg-slate-700 py-2">画像を選び直す</button></div>:<button type="button" onClick={()=>inputRef.current?.click()} className="flex w-full flex-col items-center rounded-xl border-2 border-dashed border-emerald-500/50 py-10 text-emerald-400"><Upload/><b>リザルト画像を選択</b><span className="text-xs">1枚</span></button>}<input ref={inputRef} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>void choose(e.target.files?.[0]??null)}/></div><button disabled={!preparedImage||preparing||busy} onClick={async()=>{if(!preparedImage||analysisInFlight.current)return;analysisInFlight.current=true;const current=generation.current;try{const analyzed=await onAnalyze(preparedImage.uploadFile);if(current!==generation.current)return;setResult(analyzed);setDirty(true);setResultDirty(true);setAnalysisApplied(true);}catch{/* Parent displays the API error and preserves the current form. */}finally{analysisInFlight.current=false;}}} className="flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-600 py-4 font-bold disabled:opacity-40">{preparing?<><Loader2 className="animate-spin"/>画像を準備中...</>:busy?<><Loader2 className="animate-spin"/>解析中...</>:"AIで勝敗を解析する"}</button></>}
    {result&&<div className="space-y-2 rounded-xl bg-emerald-950/20 p-4" data-analysis-complete={issues.length===0&&Boolean(winner)}><h3 className="font-black">解析結果（プレビュー）</h3>{analysisApplied&&<p role="status" className="rounded-lg bg-blue-950/50 p-3 text-sm font-bold text-blue-200">解析結果を反映しました。保存するまで確定されません。</p>}{[...result.rounds].sort((a,b)=>a.roundNumber-b.roundNumber).map(round=><div key={round.roundNumber} className="grid grid-cols-[2rem_3rem_1fr_3rem] items-center gap-2 rounded-lg bg-slate-800/70 p-3 text-center sm:grid-cols-[3rem_1fr_1.5fr_1fr]"><b>R{round.roundNumber}</b><span className={round.winner==="left"?"font-black text-blue-400":"text-slate-500"}>{round.winner==null?"-":round.winner==="left"?"WIN":"LOSE"}</span>{disabled?<span className="text-xs text-slate-300">{round.winner==="left"?`${attacker.name}（左）の勝利`:round.winner==="right"?`${defender.name}（右）の勝利`:"未判定"}</span>:<select aria-label={`ラウンド${round.roundNumber}の勝者`} disabled={busy} value={round.winner??""} onChange={e=>updateRound(round.roundNumber,e.target.value==="left"||e.target.value==="right"?e.target.value:null)} className="min-w-0 rounded-lg bg-slate-950 p-2 text-xs"><option value="">未判定</option><option value="left">{attacker.name}（左）の勝利</option><option value="right">{defender.name}（右）の勝利</option></select>}<span className={round.winner==="right"?"font-black text-red-400":"text-slate-500"}>{round.winner==null?"-":round.winner==="right"?"WIN":"LOSE"}</span></div>)}<p className="pt-2 text-center text-lg font-black text-emerald-300">{winner?`${winner==="left"?attacker.name:defender.name}の勝利`:"勝者未確定"}</p>{issues.length>0&&<ul className="text-sm text-red-300">{issues.map(issue=><li key={issue}>・{issue}</li>)}</ul>}{!disabled&&<button disabled={busy||issues.length>0||!winner} onClick={async()=>{if(existing&&!window.confirm("登録済みの勝敗を上書きしますか？"))return;if(!existing&&!window.confirm("この内容で勝敗を登録しますか？"))return;try{await onSave(result);setAnalysisApplied(false);setResultDirty(false);await choose(null,true);}catch{/* Parent displays the API error and keeps edits. */}}} className="w-full rounded-xl bg-blue-600 py-4 font-bold disabled:opacity-40">この内容で勝敗を登録する</button>}</div>}
    {onClose&&<button disabled={busy} onClick={close} className="w-full rounded-xl bg-slate-800 py-3">勝敗登録を閉じる</button>}
  </section>;
}
