"""Add advanced character metadata

Revision ID: 0db9f4fa777e
Revises: d1e9ecf1fd5c
Create Date: 2026-04-28 10:55:19.948803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0db9f4fa777e'
down_revision: Union[str, Sequence[str], None] = 'd1e9ecf1fd5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('weapon', sa.String(), nullable=True))
    op.add_column('characters', sa.Column('element', sa.String(), nullable=True))
    op.add_column('characters', sa.Column('burst_phase', sa.String(), nullable=True))
    op.add_column('characters', sa.Column('manufacturer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'manufacturer')
    op.drop_column('characters', 'burst_phase')
    op.drop_column('characters', 'element')
    op.drop_column('characters', 'weapon')
    # ### end Alembic commands ###
