"""add season and owner_name

Revision ID: 39a682ac2a94
Revises: de4c96e9485a
Create Date: 2026-06-19 11:06:22.757259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39a682ac2a94'
down_revision: Union[str, Sequence[str], None] = 'de4c96e9485a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('season', sa.String(), nullable=True))
    op.add_column('tournaments', sa.Column('owner_name', sa.String(), nullable=True))
    # op.drop_column('tournaments', 'owner_seed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('tournaments', sa.Column('owner_seed', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tournaments', 'owner_name')
    op.drop_column('tournaments', 'season')
    # ### end Alembic commands ###
