"""add play_server to app_users

Revision ID: 7e2667a37d93
Revises: d3a8e5f7b9c1
Create Date: 2026-06-29 03:23:20.588152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e2667a37d93'
down_revision: Union[str, Sequence[str], None] = 'd3a8e5f7b9c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE "app_users" ADD COLUMN IF NOT EXISTS play_server VARCHAR')
    op.drop_constraint(op.f('app_users_email_key'), 'app_users', type_='unique')
    op.drop_index(op.f('ix_app_users_email'), table_name='app_users')
    op.create_index(op.f('ix_app_users_email'), 'app_users', ['email'], unique=True)
    op.alter_column('championships', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_championships_id'), 'championships', ['id'], unique=False)
    op.drop_constraint(op.f('championships_created_by_fkey'), 'championships', type_='foreignkey')
    op.create_foreign_key(None, 'championships', 'app_users', ['created_by'], ['id'])
    op.drop_constraint(op.f('tournaments_championship_id_fkey'), 'tournaments', type_='foreignkey')
    op.drop_constraint(op.f('tournaments_created_by_fkey'), 'tournaments', type_='foreignkey')
    op.create_foreign_key(None, 'tournaments', 'championships', ['championship_id'], ['id'])
    op.create_foreign_key(None, 'tournaments', 'app_users', ['created_by'], ['id'])
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.execute("UPDATE users SET hashed_password = password WHERE password IS NOT NULL")
    op.execute("UPDATE users SET hashed_password = '' WHERE hashed_password IS NULL")
    op.alter_column('users', 'hashed_password', nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('users', 'hashed_password')
    op.drop_constraint(None, 'tournaments', type_='foreignkey')
    op.drop_constraint(None, 'tournaments', type_='foreignkey')
    op.create_foreign_key(op.f('tournaments_created_by_fkey'), 'tournaments', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('tournaments_championship_id_fkey'), 'tournaments', 'championships', ['championship_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'championships', type_='foreignkey')
    op.create_foreign_key(op.f('championships_created_by_fkey'), 'championships', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_championships_id'), table_name='championships')
    op.alter_column('championships', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_app_users_email'), table_name='app_users')
    op.create_index(op.f('ix_app_users_email'), 'app_users', ['email'], unique=False)
    op.create_unique_constraint(op.f('app_users_email_key'), 'app_users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('app_users', 'play_server')
    # ### end Alembic commands ###
