"""add play_server to app_users

Revision ID: 7e2667a37d93
Revises: d3a8e5f7b9c1
Create Date: 2026-06-29 03:23:20.588152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e2667a37d93'
down_revision: Union[str, Sequence[str], None] = 'd3a8e5f7b9c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE "app_users" ADD COLUMN IF NOT EXISTS play_server VARCHAR')
    
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    
    app_users_constraints = {c["name"] for c in inspector.get_unique_constraints("app_users")}
    if "app_users_email_key" in app_users_constraints:
        op.drop_constraint("app_users_email_key", "app_users", type_="unique")
        
    op.execute("DROP INDEX IF EXISTS ix_app_users_email")
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_app_users_email ON app_users (email)")
    
    op.alter_column('championships', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
               
    op.execute("CREATE INDEX IF NOT EXISTS ix_championships_id ON championships (id)")
    
    championships_fks = {fk["name"] for fk in inspector.get_foreign_keys("championships")}
    if "championships_created_by_fkey" in championships_fks:
        op.drop_constraint("championships_created_by_fkey", "championships", type_="foreignkey")
    op.create_foreign_key(None, 'championships', 'app_users', ['created_by'], ['id'])
    
    tournaments_fks = {fk["name"] for fk in inspector.get_foreign_keys("tournaments")}
    if "tournaments_championship_id_fkey" in tournaments_fks:
        op.drop_constraint("tournaments_championship_id_fkey", "tournaments", type_="foreignkey")
    if "tournaments_created_by_fkey" in tournaments_fks:
        op.drop_constraint("tournaments_created_by_fkey", "tournaments", type_="foreignkey")
    op.create_foreign_key(None, 'tournaments', 'championships', ['championship_id'], ['id'])
    op.create_foreign_key(None, 'tournaments', 'app_users', ['created_by'], ['id'])
    
    op.execute('ALTER TABLE "users" ADD COLUMN IF NOT EXISTS hashed_password VARCHAR')
    
    users_columns = {col["name"] for col in inspector.get_columns("users")}
    if "password" in users_columns:
        op.execute("UPDATE users SET hashed_password = password WHERE password IS NOT NULL")
        op.drop_column('users', 'password')
        
    op.execute("UPDATE users SET hashed_password = '' WHERE hashed_password IS NULL")
    op.alter_column('users', 'hashed_password', nullable=False)
    
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
               
    users_constraints = {c["name"] for c in inspector.get_unique_constraints("users")}
    if "users_email_key" in users_constraints:
        op.drop_constraint("users_email_key", "users", type_="unique")
        
    op.execute("DROP INDEX IF EXISTS ix_users_email")
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_users_email ON users (email)")
    
    op.execute("DROP INDEX IF EXISTS ix_users_id")
    op.execute("CREATE INDEX IF NOT EXISTS ix_users_id ON users (id)")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('users', 'hashed_password')
    op.drop_constraint(None, 'tournaments', type_='foreignkey')
    op.drop_constraint(None, 'tournaments', type_='foreignkey')
    op.create_foreign_key(op.f('tournaments_created_by_fkey'), 'tournaments', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('tournaments_championship_id_fkey'), 'tournaments', 'championships', ['championship_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'championships', type_='foreignkey')
    op.create_foreign_key(op.f('championships_created_by_fkey'), 'championships', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_championships_id'), table_name='championships')
    op.alter_column('championships', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_app_users_email'), table_name='app_users')
    op.create_index(op.f('ix_app_users_email'), 'app_users', ['email'], unique=False)
    op.create_unique_constraint(op.f('app_users_email_key'), 'app_users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('app_users', 'play_server')
    # ### end Alembic commands ###
