"""add seed_number to player

Revision ID: d1e9ecf1fd5c
Revises: 50a565ba381c
Create Date: 2026-04-27 04:56:50.943362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e9ecf1fd5c'
down_revision: Union[str, Sequence[str], None] = '50a565ba381c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('seed_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'seed_number')
    # ### end Alembic commands ###
