"""add unique constraint on player tournament_id and seed_number

Revision ID: de4c96e9485a
Revises: 0db9f4fa777e
Create Date: 2026-05-20 11:37:59.676518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de4c96e9485a'
down_revision: Union[str, Sequence[str], None] = '0db9f4fa777e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_player_tournament_seed', 'players', ['tournament_id', 'seed_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_player_tournament_seed', 'players', type_='unique')
    # ### end Alembic commands ###
